name = "finvantage-web"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
main = "server/index.ts"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "finvantage_d1"
database_id = "89b48482-61cc-48b8-b2b8-7ca9410ba21e"
migrations_dir = "drizzle"